services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: comboapp
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    backend:
        build: ./comboapp
        depends_on:
            - db
        restart: on-failure
        ports:
            - "8080:8080"

    frontend:
        build: ./frontend
        depends_on:
            - backend
        ports:
            - "3000:3000"